language: node_js
branches: 
  only:
      - master
node_js:
    - "6.11.0"
install:
    - npm install
script:
    - npm test
services:
  - postgresql
cache: 
  - npm install
before_script:
  - createuser Ifeanyi -s -U postgres
  - createdb postit-dev --username=Ifeanyi
  - sequelize db:migrate