language: node_js
branches: 
  only:
      - master
services: # enable various services
  - postgres
node_js:
    - "0.10"
script: 
  
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install