language: node_js
branches: 
  only:
      - master
node_js:
    - "6.11.0"
install:
    - npm install
script:
    - npm test
services:
  - postgresql
before_script:
  - psql -c 'create database postit-dev;' -U Ifeanyi