import keymirror from 'keymirror';

export default keymirror({
  REGISTER_SUCCESS: null,
  REGISTER_FAILURE: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,
  CREATE_GROUP_SUCCESS: null,
  UPDATE_GROUP_MEMBERS_SUCCESS: null,
  SEND_MESSAGE_SUCCESS: null,
  SEND_MESSAGE_FAILURE: null,
  SEARCH_USERS_SUCCESS: null,
  SEARCH_USERS_FAILURE: null,
  SELECT_GROUP_SUCCESS: null,
  SELECT_GROUP_FAILURE: null,
  LOAD_MESSAGES_SUCCESS: null,
  LOAD_MESSAGES_FAILURE: null,
  LOAD_GROUPS_SUCCESS: null,
  LOAD_GROUPS_FAILURE: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,
  REQUEST_PASSWORD_CHANGE_SUCCESS: null,
  REQUEST_PASSWORD_CHANGE_FAILURE: null,
});
